### ISSUE TITLE
MemoryError on M0 boards

### ISSUE THREAD

**Issue by deshipu** [adafruit/Adafruit_CircuitPython_SharpMemoryDisplay#2]
```python
Traceback (most recent call last):
  File "main.py", line 6, in <module>
  File "adafruit_sharpmemorydisplay.py", line 50, in <module>
MemoryError: memory allocation failed, allocating %u bytes
```

**Comment by ladyada** [comment]
what size screen is this?

**Comment by deshipu** [comment]
96x96

**Comment by ladyada** [comment]
are you running all mpy's?

**Comment by deshipu** [comment]
gotcha! I was running .py's
